db changes according to db schema in discord
Saber-Quest/SaberQuest-Backend pull request #6
Opened 2023-08-28 14:50 UTC by raineio

2023-09-04 01:31 UTC, wolfcomp requested changes
Fix the different linting errors and it looks fine.

2023-09-04 22:07 UTC, wolfcomp requested changes

2023-09-04 22:07 UTC, wolfcomp commented on src/functions/random.ts
> +        token += characters.charAt(Math.floor(Math.random() * characters.length));
`Math.random` does not provide a [cryptographic stable](https://dev.to/darkmavis1980/random-numbers-in-node-js-with-crypto-4agg) token.

2023-09-04 22:07 UTC, wolfcomp commented on src/functions/random.ts
> +        state += characters.charAt(Math.floor(Math.random() * characters.length));
`Math.random` does not provide a [cryptographic stable](https://dev.to/darkmavis1980/random-numbers-in-node-js-with-crypto-4agg) state

2023-09-05 17:33 UTC, wolfcomp requested changes

2023-09-05 17:33 UTC, wolfcomp commented on src/api/login/login.ts
> +                    redirect_uri: "https://saberquest.xyz/login/beatleader",
Do not hard code redirect URIs

2023-09-05 21:26 UTC, wolfcomp approved these changes

2023-09-05 21:50 UTC, StormPacer approved these changes

2023-09-05 21:50 UTC, merged